### ISSUE TITLE
Identifying sources and sinks from AndroidManifest.xml

### ISSUE THREAD

**Issue by jiwonjoung** [secure-software-engineering/FlowDroid#152]
Hello, 
I have an AndroidManifest.xml file and would like to customize the default sourcesandsinks.txt file for my application. 

However, I am new to Android and am having trouble reading the AndroidManifest.xml file and the sourcesandsinks.txt file. 

It seems like there are two "types" of annotations: 
The first type has some data between < // stuff here > 
```<android.location.LocationManager: android.location.Location getLastKnownLocation(java.lang.String)> -> _SOURCE_```

The other type has some additional data after the carats <//stuff here> : more stuff
```<android.telephony.TelephonyManager: java.lang.String getDeviceId()> android.permission.READ_PHONE_STATE -> _SOURCE_```

What is the difference and how can I find these fields to create custom items? 
Is the a tool I can use to automatically create a custom sourcesandsinks file based on an app apk? 

Thanks in advance. . . !

**Comment by StevenArzt** [comment]
Sources and sinks are independent from a particular APK file and have nothing to do with the manifest file. A source specifies which data you are interested in and want to track across the app. A sink denotes where this data should arrive for you to be motified. FlowDroid reports when a given app reads data from one of your sources and passes them to one of your sinks. For each such connection, you get the pair of source and sink.

In the definition file for sources and sinks, FlowDroid can optionally have a permission annotation. You can safely ignore this annotation and go with the simple format:

```
<android.location.LocationManager: android.location.Location getLastKnownLocation(java.lang.String)> -> _SOURCE_
```

We only have the additional data, because other tools use the same data format. FlowDroid does not require permission data.

**Comment by jiwonjoung** [comment]
I see -- I am trying to run flowdroid on a pool of apps. 
Is it acceptable as a  standard to use the default sourcesandsinks.txt file to analyze my apps? 
Why would someone add a new source/sink to the file? (i.e.  what motivates them to do so? )
If I want to add a new source/sink to the file, how is the proper annotation generated/created?

**Comment by StevenArzt** [comment]
You can start with default source/sink file, that's fine. People modify the file if they are interested in a different set of sensitive APIs. If you are looking for privacy violations, you will usually configure sources that obtain the user's telephone number or other personal data. If you are interested in injection vulnerabilities, you will usually rather configure incoming intents or data loaded from the Internet as sources. the source/sink definition is your problem definition for the data flow analysis.

To specify your own sources or sinks, you can take the existing ones as an example. They use Soot's format for method signatures. You first have the class name, then the return type, the method name, and the parameter type list. After the arrow, you specify whether the respective method shall be considered a source or a sink.
