### ISSUE TITLE
Interpreting output

### ISSUE THREAD

**Issue by jiwonjoung** [secure-software-engineering/FlowDroid#154]
How can I best interpret/use the flowdroid output? The output tells me that an app I am interested in analyzing has N leaks. Is there a way to see what data is being leaked or what method is responsible for leaking the data? 

Can anyone link me to any real world uses of Flowdroid? Perhaps, is there a paper that uses Flowdroid to motivate further analysis?

**Comment by StevenArzt** [comment]
FlowDroid gives you the set of source-to-sink connections:

```
[main] INFO soot.jimple.infoflow.android.SetupApplication$InPlaceInfoflow - The sink virtualinvoke $r4.<android.telephony.SmsManager: void sendTextMessage(java.lang.String,java.lang.String,java.lang.String,android.app.PendingIntent,android.app.PendingIntent)>("+49", null, $r2, null, null) in method <de.ecspride.Button1: void sendMessage(android.view.View)> was called with values from the following sources:
[main] INFO soot.jimple.infoflow.android.SetupApplication$InPlaceInfoflow - - $r4 = virtualinvoke $r3.<android.telephony.TelephonyManager: java.lang.String getDeviceId()>() in method <de.ecspride.Button1: void onCreate(android.os.Bundle)>
```

This message tells you that data flows from the source ```getDeviceId()``` is propagated to the sink ```sendTextMessage()```. The full message also tells you in which method the source and sink methods are called.

If you want to process the FlowDroid results inside your own program or analysis, it's much better to use FlowDroid as an API instead of parsing the textual command-line output. You can find the results in the ```InfoflowResults``` class.

```
InfoflowAndroidConfiguration config = new InfoflowAndroidConfiguration();
config.getAnalysisFileConfig().setAndroidPlatformDir(androidJarPath);
config.getAnalysisFileConfig().setTargetAPKFile(apkPath);
config.setMergeDexFiles(true);

SetupApplication analyzer = new SetupApplication(config);
InfoflowResults results = analyzer.runInfoflow();
```
