### ISSUE TITLE
No call graph in Scene (false system classes)

### ISSUE THREAD

**Issue by JordanSamhi** [secure-software-engineering/FlowDroid#171]
Hello @StevenArzt,

I experienced some analysis with no call graph in Scene with particular apps, I think I found the problem, take a look at this **simplified** activity declaration : 

```
<?xml version="1.0" package="com.android.security">
     <application android:debuggable="true" android:icon="@drawable/ic_launcher" android:label="@string/app_name">
         <activity android:label="@string/app_name" android:name=".MainActivity">
         </activity>
     </application>
</manifest>
```

We can see that the full name of the activity is "com.android.security.MainActivity"

Now take a look at checkAndAddComponent method in Flowdroid : 

```
private void checkAndAddComponent(Set<String> entryPoints, AXmlNode node) {
    AXmlAttribute<?> attrEnabled = node.getAttribute("enabled");
    if (attrEnabled == null || !attrEnabled.getValue().equals(Boolean.FALSE)) {
        AXmlAttribute<?> attr = node.getAttribute("name");
            if (attr != null) {
                String className = expandClassName((String) attr.getValue());
                if (!SystemClassHandler.isClassInSystemPackage(className))
                    entryPoints.add(className);
            } else {
                // This component does not have a name, so this might be
                // obfuscated malware. We apply a heuristic.
                for (Entry<String, AXmlAttribute<?>> a : node.getAttributes().entrySet()) {
                    AXmlAttribute<?> attrValue = a.getValue();
                    if (attrValue != null) {
                        String attrValueName = attrValue.getName();
                        if ((attrValueName == null || attrValueName.isEmpty())
                                && attrValue.getType() == AxmlVisitor.TYPE_STRING) {
                            String name = (String) attrValue.getValue();
                            if (isValidComponentName(name)) {
                                String expandedName = expandClassName(name);
                                if (!SystemClassHandler.isClassInSystemPackage(expandedName))
                                    entryPoints.add(expandedName);
                            }
                        }
                    }
                }
            }
        }
    }
```

The piece of code we are interested in is this one : 

```
AXmlAttribute<?> attr = node.getAttribute("name");
    if (attr != null) {
        String className = expandClassName((String) attr.getValue());
        if (!SystemClassHandler.isClassInSystemPackage(className))
            entryPoints.add(className);
    }
```

attr get the value : name="com.android.security.MainActivity", so it is not null, then className get the value : com.android.security.MainActivity
Then a check is performed on this name, this is the code of the check : 

```
public static boolean isClassInSystemPackage(String className) {
        return className.startsWith("android.") || className.startsWith("java.") || className.startsWith("javax.")
                || className.startsWith("sun.") || className.startsWith("org.omg.")
                || className.startsWith("org.w3c.dom.") || className.startsWith("com.google.")
                || className.startsWith("com.android.");
}
```

We clearly see the problem here, it is assumed that if the className startsWith "com.android." it is a system class, so the class is not added as an entrypoint. But in this case, the className startsWith "com.android." as it is equals to "com.android.security.MainActivity" but is not a system class.
I think the heuristic is not precise enough.

It is very likely that in #139 it is the same issue as the main activity of @BushraAloraini app is called "com.google.sample.echo.MainActivity".

**Comment by dusby** [comment]
@StevenArzt 
As a matter of fact, could you please detail what was the idea behind this check at this moment ? 
If I want to analyze a real system class, it seems impossible, right ?

**Comment by StevenArzt** [comment]
Thanks for your really helpful analysis, @dusby. The general idea behin the heuristic was to save analysis time and memory by not looking into components that have not been implemented by the app developer, but that are rather part of the Android framework or some commonly used library. For most normal apps, many users are not interested in flows inside these components anyway, since you can't tell an app developer to fix some information leakage that he isn't responsible for in the first place, and the chances of telling Google to change the OS are limited.

I do understand that there are use cases in which you want to analyze flows through system components nonetheless. 2ec4cb2185f3707de9481eb2df8379b2097b7f66 should do the trick. We now only exclude such components if FlowDroid is configured to ignore flows in system packages, an option that has already been around for some time.

**Comment by dusby** [comment]
Thank you @StevenArzt for your quick response !
I understand the purpose here.

But the main problem here was not to force the retrieving of components if there **are** system classes but rather to authorize the retrieving of components if they **look like** system classes but are not. That is why I think a check has been forgotten in your commit 2ec4cb2, I opened a PR #172 to fix this.
Because I still had the same problem, but not with this fix.

I have an other observation here : 
This solution is *pretty* but maybe too permissive ?
Let me explain : if I turn off the ignoring of system packages like this : 

```
InfoflowAndroidConfiguration ifac = new InfoflowAndroidConfiguration();
ifac.setIgnoreFlowsInSystemPackages(false);
```

This fix would allow to analyze any classes one need if they **look like** system classes but are not. But it will also allow the analysis of **real** system classes, that would be a big load for the app. Maybe a better solution would be to actually do the difference between a real system app and a *false* one (that would also take computation time, but maybe less than analyzing the entire component ?)

**Comment by StevenArzt** [comment]
In fact, distinguishung between actual application code and "the rest" (system classes. third-party libraries, compiler service classes, runtime environemt classes, etc.) is highly non-trivial and a field of research on its own. We employ a simple heuristic based on the package name, which is usually good enough. If you are analyzing some app by developer X, who is not Google, assuming him to not put any classes into a package that starts with "com.google" is reasonable. We only get into issues if you actually want to analyze a system app, or some app that was developed by Google and therefore also uses "com.google" package names, without these classes being a real Android system classes.

In one of our commercial projects, we replaced the hard-coded list of package name prefixes with an automatically-computed list of libraries collected from Maven artefacts. With essentially a complete dump of Maven Central, we were able to more precisely find longer prefixes that denote library classes, but nothing else. However, even this approach isn't fully fool-proof, and we can't make it available.

One might also try to collect the names of each individual system class from the respective library JAR files. That would, however, most likely be an under-approximation and would lead to a huge database of class names.

Good ideas on better solutions are always welcome.

**Comment by dusby** [comment]
Yes you're right this is non-trivial, that would mean solve the problem of distinguishing a benign app and a malware app actually.

Do you think that if the component, even detected as system class (because starting with "com.android.xxx"), is in the manifest file, we could considere it as **not** a system app ? That would be a better approximation, or am I missing something ?

**Comment by StevenArzt** [comment]
The question is not so much about system _apps_, but rather system _classes_ or _components_ inside an app. A system app is usually signed with a system key, so we could simply collect a whitelist of signing keys for various Android versions and device manufacturers for that matter. If we're talking about classes, things get more complicated. Normal apps integrate libraries such as Firebase with multiple components that also appear inside the manifest. The idea is to have a means to skip them during analysis, while still processing the rest of the app.

**Comment by dusby** [comment]
Yes sorry I meant system classes (lapsus) not apps.

Yes I see, that is why supposing it being in the manifest is finally not a good idea.

Anyway thank you for your clear responses about this problem.

**Comment by dusby** [comment]
I proposed a PR in #175, because I tested this morning with a false system class I need for my tests and the problem did not seem to be resolved. Indeed, the component appeared but not its life-cycle, so the app could not be analyzed. 
What I did is simple : 
![fix](https://user-images.githubusercontent.com/35679728/60433242-a09da900-9c04-11e9-99e9-dc88d0d033ef.png)
I moved the manifest variable upward and now all subclasses of sublasses of AbstractAndroidEntryPointCreator have access to it, they can now use the isExcluded(className) method.

**Comment by StevenArzt** [comment]
Thanks for the good work. I have already accepted your merge request. You're right, there are more positions in the code that check for exclusions, so your fix absolutely makes sense.

**Comment by dusby** [comment]
You are very reactive, thank you.
The other checks do not bother for the moment, but if it is the case they are to be modified too, maybe on a case-by-case basis.

**Comment by dusby** [comment]
Hello @StevenArzt 

What do you think about this : 

```java
public boolean isClassInSystemPackage(String className) {
    return (className.startsWith("android.") || className.startsWith("java.") || className.startsWith("javax.")
        || className.startsWith("sun.") || className.startsWith("org.omg.")
        || className.startsWith("org.w3c.dom.") || className.startsWith("com.google.")
        || className.startsWith("com.android.")) 
        && !Scene.v().getSootClass(className).isApplicationClass();
}
```
Instead of turning on and off a boolean, we could simply look if the tested class appears in application classes ? That way false system classes would not be detected as system classes because they appear in application classes.

What is your opinion ?

**Comment by StevenArzt** [comment]
That wouldn't really solve the problem for, e.g., the Android support classes, because those classes are compiled into each app, but are not developer code, i.e., we don't really want to analyze them. In fact, in one of our commercial projects, we filter out all classes that are from well-known library packages, regardless of whether they are part of the APK or not.

**Comment by dusby** [comment]
Ok I see, one really has to use addtionnal heuristics to filter out what she wants to analyze. Thank you for the insight.
