### ISSUE TITLE
ARSCFileParser maps all resources to the same resourceId for certain obfuscated APKs

### ISSUE THREAD

**Issue by jpstotz** [secure-software-engineering/FlowDroid#202]
Using FlowDroid's ARSCFileParser  to parse `resources.arsc` of [Facebook messenger 231.0.0.25.121 (170889108)](https://apkpure.com/de/facebook-messenger/com.facebook.orca/download/170889108-APK?from=variants%2Fversion) ends up with all resources mapped onto the same resourceId.

Of course this makes it later impossible to resolve and resource by it's ID (e.g. resource references in the AndroidManifest.xml).

This is caused by the obfuscation Facebook uses: The resources are obfuscated in a way that every entry points to the same resource name "`(name removed)`".

This is caused by the logic that ARSCFileParsers first queries the resourcename-table if a resource of that name is already known and if yes this resourceId is used. [relevant source code section](https://github.com/secure-software-engineering/FlowDroid/blob/master/soot-infoflow-android/src/soot/jimple/infoflow/android/resources/ARSCFileParser.java#L2212).

Simply removing this section (L2212-2220) solves my problem with the Facebook apps, however I am not sure what functionality it actually breaks. Usually extra logic has a special purpose. 

@StevenArzt Do you remember what purpose this code has? 

While testing some non-obfuscated APKs I did not encounter that this code section was ever activated and it generated a resourceId different to the one calculated by the default formula `res.resourceID = (packageTable.id << 24) + (typeTable.id << 16) + resourceIdx;` (except for the obfuscated Facebook APKs where it causes problems of course).

**Comment by StevenArzt** [comment]
That's actually a very good question. It was me who wrote the code, but I don't remember. The comment in the code seems to indicate that multiple resources with the same name should end up with the same resource ID instead of getting a new one (by increasing the resource index for every entry). This code seems to have existed from the very first commit of ´`ARSCFileParser``. I'd suggest to just get rid of it. Can you create a merge request?
