### ISSUE TITLE
Can I use FlowDroid to perform forward/backward slicing based on a certain annotated variable?

### ISSUE THREAD

**Issue by ANter-xidian** [secure-software-engineering/FlowDroid#210]
Hi, dear Steven Arzt & Eric Bodden

I am currently working on a Java project that aims to perform a forward/backward slicing technique using the Soot framework.

The global picture of my project is to convert some bytecode files to Jipmle forms and then perform forward/backward slicing based on a certain annotated variable(s).
As it's known that the Soot framework doesn't support any kind of slicing technique.

I wonder if I can use **FlowDroid** to achieve the following two points:

**1.** Annotate a specific variable in my Java code?

**2.**  Perform forward/backward slicing based on the annotated variable(s) in my Java project programmatically?

Please guide me on how to do so using **FlowDroid**.

Thanks in advance.

**Comment by StevenArzt** [comment]
FlowDroid is a static data flow tracker, not a slicer. I'd say that FlowDroid is simply not the tool you are looking for.

There is a certain similarity between the two concepts, but it's not trivial. In that notation, the value tainted by the source would be the slicing criterion. FlowDroid tracks taints forward through the interprocedural control flow graph (ICFG). Each statement that transforms a taint abstraction could be seen as part of a forward slice. However, since FlowDroid is a taint tracker, it doesn't distinguish between statements that simply pass on taints (because they, e.g., do not reference the tainted value at all) and those that actively transform one taint abstraction into another. You would need to extend the implementation to build a grapf of taint-transforming statements while computing the IFDS flow functions. It might very well be easier to implement a slicer from scratch, though.

**Comment by ANter-xidian** [comment]
Dear @StevenArzt, I clearly got your point.
I do appreciate your reply.

Regards,
