### ISSUE TITLE
Where are the generated API summaries?

### ISSUE THREAD

**Issue by izgzhen** [secure-software-engineering/FlowDroid#273]
From what I can see, https://github.com/secure-software-engineering/FlowDroid/tree/develop/soot-infoflow-summaries/summariesManual contains "manually" written sumamries (since the name of that directory reads like so), but I wonder where the generated ones are (as in the stubdroid work).

Thanks!

**Comment by StevenArzt** [comment]
You can have a look at the ``TestSummaries`` folder. In practice, we have found these summaries to be correct, but overly precise. They represent every minor implementation detail. For example, look at type-safe “Intent” implementations. You can add extras of various different types, and it would be perfectly correct to have one flow for storing an Integer value into some Integer field, one for storing some string in a string field, etc. When reading out data, you would also have one flow per data type, each from the respective field to the return value of the getter. That’s essentially what the code does. However, it’s unnecessarily complex. The semantics we need is “you put in some extra, and you get it back”. You can encode the same behavior using a single flow for storage and a single flow for retrieval. Less (fake) fields in memory, fewer different data flows, more re-usable IFDS summaries. At some point, we need to work on automatic generalization of data flows, but that’s a non-trivial feat. For the time being, we resort to hand-optimized summaries. Even if they came out of StubDroid at some point, someone looked at the XML files and made sure they were compact. That’s why the folder is called “summariesManual”, and why we constantly add new summaries, instead of having thousands right from the start. As I said, there’s work going on to, at some point in the future, get rid of the manual optimization, but we’re not there yet. Of course, if you don’t care so much about performance and memory consumption, you can also be totally fine with the StubDroid output as it is.

**Comment by izgzhen** [comment]
Thanks for the prompt response! Is `TestSummaries` a subset for testing purpose or the full set? (it contains much less files than `summariesManual`).

**Comment by StevenArzt** [comment]
The ``testSummaries`` folder is created and maintained by the test cases. We do not have the full set of auto-generated summaries in the repository, because we didn't want to make the repository huge, especially since most people now use the hand-optimized summaries. Note we don't write the manual summaries from scratch, though. When a new one is needed, we run StubDroid on that particular class, and then optimize the output file where necessary.

**Comment by izgzhen** [comment]
That's very clear, thanks!
