### ISSUE TITLE
Can call flows be retrieved instead of data flows as the result? 

### ISSUE THREAD

**Issue by amohar** [secure-software-engineering/FlowDroid#324]
Hello! I was testing Flowdroid today and an interesting problem popped up. While I was getting valuable data flows, there were situations where a code path existed between an interesting source and sink that had value to me, but they weren't tainted by each other, so of course, they weren't reported.

That's when I started thinking, could Flowdroid be used to get the call flows between sources and sinks instead of just data flows. It would be much more precise than the plain xref tree outgoing from a source because the whole Android lifecycle is modeled, so this could include any callbacks and similar implicit calls.

Please let me know if this is doable or if there are other ideas on how to achieve this. Thanks!

**Comment by radegand** [comment]
I was wondering the very same thing. :-)
Is there a way to trace only calls to a specific sink? (be it android API or a method in the app class, providing specific JAR of course)
Alternatively, how difficult would it be to modify FlowDroid or add such functionality and where would one start?
Thanks in advance for any hints.

**Comment by StevenArzt** [comment]
I don't fully understand your question. FlowDroid looks for flows between sources and sinks. You may have a control flow path between a source statement and a sink statement, but that doesn't mean that there is any leak. Take the following example:

```
String s = source();
String t = "";
sink(t);
```

In the example, the program's control flow starts at the source, and reaches the sink, but no data from the source is leaked.

If you have examples in which FlowDroid does not find a proper leak, that's a problem we need to address. Maybe there's a summary missing. Over-approximating via the ICFG is not an option and would lead to many false positives.

Note that FlowDroid already models Android lifecycle APIs and callbacks. That's why we create the dummy main method in our ``AndroidEntryPointCreator``. If you want to track implicit flows, there's an option for it that you can enable in the FlowDroid settings.

If, for some other use case beyond taint tracking, you still need  to find whether there is a control flow path between two statements, you can use FlowDroid to create a callgraph and then use the ICFG (``InfoflowCFG``) for performing tree searches on the control flow. So yes, it is possible with FlowDroid.

**Comment by amohar** [comment]
@StevenArzt thank you so much for your comment. I believe the last two paragraphs answer my question. I had an example where the data wasn't actually being leaked, but there was a control path flow between the source and the sink. The source was influencing a switch which was the main switch whether the sink is going to be called or not. What is great to me about the FlowDroid approach is that as it models the Android lifecycle it can detect control flows more precisely. I'll definitely try out what you suggested.

@radegand I guess it depends on what you mean by a "specific sink". If by this you mean a specific line in a specific method, it would be enough to search all the results that have that specific sink. If you mean a specific sink as a call to a method anywhere in the code, you could maybe leverage categories where you put that sink into a category and that should separate those leaks from others (I'm a total greenhorn with FlowDroid, so I'm not even sure this is correct, but feel free to investigate). If you want all the call flows to a particular method from any Android entry point, you should probably look into setting the correct entry-point sources.

**Comment by radegand** [comment]
Hi again,
Thank you gentlemen for your responses. 
@StevenArzt , yes, it does make sense what you're saying.

I'm also a greenhorn when it comes to static analysis, so maybe I'm missing a piece of a puzzle here. I wanted to trace two custom leaks, please see the below. Because this failed, I was hoping to see a control flow graph from `onCreate()` (my _SOURCE_ effectively) to `sendTextMessage()` (my _SINK_) regardless of FlowDroid detecting an actual data flow between the two or not. Of course, having the leak detected would be even better.

I'm using asimple sample app from Android RE 101 tutorial by @maddiestone, which supposedly does SMS fraud. The app indeed makes a call to Android API `sendTextMessage()` and I wanted FlowDroid to discover the leak (I've tried two different leaks actually). The flow is pretty simple:
0) `onCreate()` makes a call to `getSimOperator()` to get SIM card provider operator and saves it as String `operator`. (**_source1_**)
1) Still inside `onCreate()` a call is made to `loginByPost(operator)` with the 'operator' as a parameter. Result of that call is saved to JSONObject inside `onCreate()`. 
2) `loginByPost()` calls `getPhoneNumber()` inside the same class.
4) `getPhoneNumber()` requests permission (using `requestPermissions()` ) to send SMS and returns.
5) `loginByPost()` makes a `HttpURLConnection()` to hardcoded URL + `operator` parameter (**_sink1_**). The response is read using `getInputStream()`, which is a predefined source (**_source2_**) inside the sample `SourcesAndSinks.txt` file. It then returns that data as a ByteArray.
6) so we're back inside `onCreate()`. But, because `getPhoneNumber()` requested permissions, we're getting a callback on `onRequestPermissionResult()`, which is overriden in the same class.
7) `onRequestPermissionResult()` checks if the permission was granted and if it was, calls `sendMessage()` (my **_sink2_**) with the parameters extracted from that `JSONObject` in `onCreate()` earlier. Thus an SMS is sent without user knowledge or consent.

I wamted to get FlowDroid to detect two data flows:
a) from **_source1_** to **_sink1_** (getting the name of network operator and sending it to the internet)
b) from **_source2_** to **_sink2_** (getting destination number and SMS body from URL and using it as parameters to `sendTextMessage()`).

But I fail on both cases :( I was wondering if the second flow is not detected because of the asynchronous calls to `requestPermissions()` and `onRequestPermissionResult()`. That's why I thought that maybe I can get a control flow graph only to `sendTextMessage()`, regardless of the taint analysis results to visualize what's going on.

Should FlowDroid be able to detect both leaks?

I defined one additional _source_ and two _sinks_ as follows:

```
<android.telephony.TelephonyManager: java.lang.String getSimOperator()> -> _SOURCE_
<java.net.HttpURLConnection: java.net.HttpURLConnection openConnection()> -> _SINK_
<android.telephony.SmsManager: void sendTextMessage(java.lang.String,java.lang.String,java.lang.String,android.app.PendingIntent,android.app.PendingIntent)> -> _SINK_
```

as I mentioned, `getInputStream()` is already defined as a _SOURCE_. I've also defined `openConnection()` as a source, but that didn't change anything.

Should you be willing to look it into yourselves, the apk file in question (careful, it's malicious), can be downloaded from here: https://github.com/jchristman/MaddieStoneAndroidRE-Docker/raw/1bf57ab8c15daefafaecd6956e15cfb9f0403f0d/samples/ThaiCamera/ThaiCamera.apk.
Any hints what am I doing wrong would be greatly appreciated. Thanks in advance.
