### ISSUE TITLE
Does the method of applyEndSummaryOnCall in IFDSSolver.java insert edges into SummaryEdge?

### ISSUE THREAD

**Issue by fanweneddie** [secure-software-engineering/FlowDroid#372]
I have read the source code of the method [applyEndSummaryOnCall](https://github.com/secure-software-engineering/FlowDroid/blob/9221109b11c1f636c0efd9fb3e9abe7e9a5de108/soot-infoflow/src/soot/jimple/infoflow/solver/fastSolver/IFDSSolver.java#L355) in `IFDSSolver.java`, but I haven't seen the operation of inserting edges into SummaryEdge in line 15.4 of [IFDS-extension algorithm](https://link.springer.com/chapter/10.1007/978-3-642-11970-5_8)(by Naeem,Lhoták and Rodriguez), 

![call_flow](https://user-images.githubusercontent.com/48879415/129467674-ce49271a-f1c1-48a9-835b-cfe8c2327845.png)

Can anyone tell me the reason? Thanks in advance!

**Comment by StevenArzt** [comment]
Have a look at the method ``addEndSummary()``.

**Comment by fanweneddie** [comment]
So it inserts edges into `EndSummary` only in the method of `ProcessExit`, right? 
If so, does it mean that the operations from line 15.2 to line 15.6 in `IFDS-extension` is redundant?

**Comment by StevenArzt** [comment]
Ah, maybe I misunderstood you. The ``addEndSummary()`` inserts edges into ``EndSummary``. The data structure that the paper calls ``SummaryEdge`` is called ``jumpFunctions`` in the ``IFDSSolver``, and is maintained in ``propagate()``.

The handling of jump functions is more complicated in FlowDroid, since we merge abstractions (concept of neighbors). In short: If the same taint arrives at the same statement from two different sources, this would normally result in two different taints being propagated. We instead merge the two and only propagate this merged taint (see call to ``addNeighbor()`` in ``propagate()``).

**Comment by fanweneddie** [comment]
Thank you for answering my questions. 
I read the source code of method `addNeighbor()` in `Abstraction.java`, but I have not seen the operation on `jumpFunctions`.
``` java
        @Override
        public boolean addNeighbor(Abstraction originalAbstraction) {
		// We should not register ourselves as a neighbor
		if (originalAbstraction == this)
			return false;

		// We should not add identical nodes as neighbors
		if (this.predecessor == originalAbstraction.predecessor && this.currentStmt == originalAbstraction.currentStmt
				&& this.predecessor == originalAbstraction.predecessor)
			return false;

		synchronized (this) {
			if (neighbors == null)
				neighbors = new TCustomHashSet<Abstraction>(NeighborHashingStrategy.INSTANCE);
			else if (InfoflowConfiguration.getMergeNeighbors()) {
				// Check if we already have an identical neighbor
				for (Abstraction nb : neighbors) {
					if (nb == originalAbstraction)
						return false;
					if (originalAbstraction.predecessor == nb.predecessor
							&& originalAbstraction.currentStmt == nb.currentStmt
							&& originalAbstraction.correspondingCallSite == nb.correspondingCallSite) {
						return false;
					}
				}
			}
			return this.neighbors.add(originalAbstraction);
		}
	}
```
So how does `addNeighbor()` maintain `jumpFunctions`？

**Comment by StevenArzt** [comment]
There are two different scenarios. If ``propagate()`` detects that the given abstraction (or any other abstraction that is ``equals()`` to it) has been seen at the given statement yet, it writes this new abstraction into ``jumpFunctions`` (line 633 contains a call to ``addFunction()``, which calls ``putIfAbsent()`` on the jump function map). If, on the other hand, we have seen the abstraction before (or some other abstraction ``equals()`` to it), we do *not* write the current one into ``jumpFunctions``, but call ``addNeighbor()`` instead.

There are some checks to ensure that we do not add neighbors if the old and new abstraction are really the same. We only want to create a neighbor if the new abstraction potentially comes from a different source. The concept is as follows: If you propagate individual abstractions, you may propagate the same data through the same method many times. Consider a method that takes input from manydifferent sources. The effect of the method on its parameters is always the same, regardless of where the caller takes the parameters from. We therefore only propagate once and only record ``jumpFunctions`` once. If we see the second call to that method (or any statement within the whole ICFG), we simply add a a neighbor and stop there, because we already know what will happen to that abstractions, since it's equivalent (``equals()``) to what he have seen before.

You can read up on the details of the topic in my PhD thesis: http://tuprints.ulb.tu-darmstadt.de/5937/.

**Comment by fanweneddie** [comment]
I will read those details, thank you for your explanation!
