### ISSUE TITLE
Taint flow with user data

### ISSUE THREAD

**Issue by canliture** [secure-software-engineering/FlowDroid#382]
Feature Request?

I want to flow taints with my `userData` from `source` to `TaintPropagationWrapper` and from `TaintPropagationWrapper` to `sink`.

I store the `userData` into `Abstraction.SourceContext.userData`, I can access the data at `TaintPropagationWrapper#getTaintsForMethod`; 

However, I can't access the data from sink point in `ISourceSinkManager#getSinkInfo`; I want to collect the data to judge whether the access path is sink point or not, but the interface method is:
```java
public SinkInfo getSinkInfo(Stmt sCallSite, InfoflowManager manager, AccessPath ap);
```
Just like the Abstraction comment says:
`The abstraction class contains all information that is necessary to track the taint.`
However, in the `ISourceSinkManager`, I just know the 3-th argument, but not the Abstraction wrapping the incoming AccessPath

**Comment by StevenArzt** [comment]
The user data is only stolred in the ``SourceContext`` by design. During the taint propagation, we do not have access to the source, nor do we have access to the user data. Only at the end, when an abstraction has been encountered at a sink statement, we track back from the sink across the taint path and reconstruct the source, a process called path building. Therefore, the sink manager cannot have this data. It would need to accept all possible sinks regardless of the user data, then path reconstruction would run (normal behavior of FlowDroid), and aftwards you can do a post-processing that filters out those data flows (once you have the final FlowDroid results, i.e., the source-to-sink connections) for which your user data does not match.

**Comment by canliture** [comment]
Thanks a lot! I think I understand the design! I will do a post-processing that filters out those data flows.

And I have a another problem. Whether `SourceContext` must be related to the source point?

If I let all the Abstraction relate to a SourceContext which records some infomation about the `Abstraction's predecessor`; Maybe the program will consume more memory(Because larger data flow domain), but the program will actually run correctly. I don't know whether my understand is right?

Thanks !

**Comment by StevenArzt** [comment]
The ``SourceContext`` is only referenced in the abstraction at the source. The other abstractions along the path have no reference to the ``SourceContext``. This is by design, because we want to re-use IFDS summaries even if the method was processed in the context of another source. This would not work if the source were part of the abstraction, as it would then also become part of the IFDS summaries, and we would have distinct propagations and summaries per source, even if the taint flows through the same method. In short, it's not only about memory, but about time consumption as well.

**Comment by canliture** [comment]
Thanks a lot again. 

I have misunderstood some concepts before.Now I think I get the thoughts by your answers.
