### ISSUE TITLE
findViewById as source by default?

### ISSUE THREAD

**Issue by linghui2016** [secure-software-engineering/FlowDroid#40]
Hi Steven,
I have used FlowDroid 2.5.1 to analyze a few real apps and sampled some of the reported leaks. I found out that there are many leaks with source _findViewById_, even when the method _findViewById_ is not defined as source in the configuration file  _SourcesAndSinks.txt_.  
I know that this method is used to get password from text field and FlowDroid exams the layout XML file to identify password field.  Is this hardcoded default source on purpose? Is there any configuration option can be used to disable it?
@StevenArzt

**Comment by StevenArzt** [comment]
The findViewById() method is treated separately, because FlowDroid needs to distinguish between various types of input fields, depending on the configured LayoutMatchingMode. The API call is always the same, but by default, FlowDroid only considers password input fields. Therefore, it needs to resolve the ID that is passed to the API call. Such a complicated treatment is not possible with a normal source/sink definition. That's why this API call has special treatment.

You can use the LayoutMatchingMode option in the InfoflowAndroidConfiguration to choose whether you would like to consider all text inputs as sources, only passwords (which is the default), or none at all.
