### ISSUE TITLE
Edges missed in the call graph, no matter what algorithm I choose to use (e.g., SPARK, CHA, etc.)

### ISSUE THREAD

**Issue by RichardHoOoOo** [secure-software-engineering/FlowDroid#474]
Hi @StevenArzt When I use FlowDroid to build a call graph, it seems there are always edges missed in the call graph, no matter what algorithm I choose to use (e.g., SPARK, CHA, etc.). The following is a simple example I use to test.

```
// onCreate() is declared in com.example.myapplication.MainActivity
protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        btn1 = (Button) findViewById(R.id.button);
        wv = (WebView) findViewById(R.id.webview);
        wv.getSettings().setJavaScriptEnabled(true);
        wv.getSettings().setSupportMultipleWindows(true);
        wv.getSettings().setJavaScriptCanOpenWindowsAutomatically(true);
        btn1.setOnClickListener(...);
        wv.loadUrl("file:///android_asset/index.html");
}
```

If I use the default call graph algorithm, which should be SPARK, it only outputs part of the methods that are invoked by `onCreate`
```
<com.example.myapplication.MainActivity$1: void <init>(com.example.myapplication.MainActivity)>
<android.app.Activity: void onCreate(android.os.Bundle)>
<android.app.Activity: void setContentView(int)>
<android.app.Activity: android.view.View findViewById(int)>
```

When I set the call graph algorithm to CHA, it outputs
```
<com.example.myapplication.MainActivity$1: void <init>(com.example.myapplication.MainActivity)>
<android.app.Activity: void onCreate(android.os.Bundle)>
<android.app.Activity: void setContentView(int)>
<android.app.Activity: android.view.View findViewById(int)>
<android.webkit.WebView: android.webkit.WebSettings getSettings()>
<android.webkit.WebView: void loadUrl(java.lang.String)>
<android.view.View: void setOnClickListener(android.view.View$OnClickListener)>
```

The result is better than that of SPARK, but calls to `setJavaScriptEnabled`, `setSupportMultipleWindows`, and `setJavaScriptCanOpenWindowsAutomatically` are still missed.

May I ask why those edges are missed by SPARK or CHA?

**Comment by RichardHoOoOo** [comment]
I see the reason why CHA misses some calls. I remember I have reported a similar [issue](https://github.com/soot-oss/soot/issues/1560#issue-815251252) in Soot. It turns out invocations on abstract or interface methods will not be included in the call graph if soot cannot find implementations of them. 

In the above mentioned case, all the methods in `WebViewSettings` are abstract methods and app developers rarely override them. Therefore, they are not captured in the call graph.

So how can I let the call graph capture those methods? Are there any options that I can set or we need to manually add those edges after the call graph is built? If one of those methods are marked as a sink, I guess FlowDroid will not report a leak because they are not included in the call graph.

**Comment by StevenArzt** [comment]
This is a Soot problem, not a FlowDroid problem. Is there a particular reason why you closed the issue in the Soot bug tracker? I guess we need some option that tells SPARK to create edges to abstract methods. That should at least fix the problem with CHA.

Now let's talk abouit SPARK. SPARK is based on type propagation. It only creates an edge from a call site to a callee, if it knows the precise type of the base object at the call site. In your case, ``setJavaScriptEnabled`` is called on the result of ``wv.getSettings()``. You normally run Soot (and thus FlowDroid) against stub implementations of the Android platform JARs. If you look into the platform JARs included with the Android SDK, you'll find that the methods don't contain actual code, and instead just throw an exception. They are merely meant for linking your apps. On the phone, there is a pre-loaded proper implementation. For our analysis, that means that SPARK cannot track the precise type of the base object. ``wv.getSettings()`` doesn't return a proper object, it always throws an exception. The base objectz on which you call ``setJavaScriptEnabled`` has no corresponding allocation site and therefore no propagated type. SPARK doesn't know the class that is precisely instantiated and in which it would look for the method. In such a case, SPARK omits the edge.

What can we do?

a) We can run against a proper Android JAR. That will give us a huge callgraph, all sorts of scalability issues, and since we still have native code, reflection, dependency injection, etc., we're not necessarily better off than before.

b) Take the immediate callee. That's what we do in our commercial code scanner [VUSC](https://www.sit.fraunhofer.de/en/offers/projekte/vusc/). If there is no callgraph edge, we simply look at the immediate callee (``getInvokeExpr().getMethod()''). In the case of Android system classes, we're not even interested in the precise (private) implementation. The abstract method is good enough.

You can also add a stage that adds fake edges to these abstract methods to the callgraph after SPARK is done, if you want to have a uniform interface to caller/callee relationships.

**Comment by RichardHoOoOo** [comment]
Hi @StevenArzt thanks for your kind reply!

I close the soot issue because I took the option B you suggest and it fixed the problem. I guess I should still take that option to fix the problem I met when using FlowDroid.

I have reopened the Soot [issue](https://github.com/soot-oss/soot/issues/1560#issue-815251252) and closed this one.
