### ISSUE TITLE
Could FlowDroid be applied to client-server applications for static taint analysis?

### ISSUE THREAD

**Issue by jimmy66688** [secure-software-engineering/FlowDroid#498]
Hi @ericbodden @StevenArzt ,
I want to perform static taint analysis on some client-server applications, but these client-server applications have one feature: there is no fixed entrypoint on the server side, and the initialization logic on the server side is separate from the request processing logic. Although I analyze all the entrypoints, the information flow is separated. Is there an idea to perform static taint analysis on server applications?
Thanks!

**Comment by StevenArzt** [comment]
Your problem is similar to Android apps, which are essentially plugins into the operating system. This design principle also applies to, e.g., Spring Boot or Java Enterprise applications. FlowDroid uses dummy main methods to simulate these interactions between platform and application, i.e., it generates a fake ``main()`` method, which calls the actual entry points.

You have multiple options:

1. You implement an instance of ``IEntryPointCreator`` from your platform (inherit from ``BaseEntryPointCreator`` to make your life easier). While this approach requires some work, you can be as precise as you want in your model, also with regard to data flows between reequest processing methods.
2. Over-approximate using the ``DefaultEntryPointCreator``, which takes a set of methods, and calls all of them in a sequence, with some heuristics on when to share objects between calls. This is a very simple solution, your mileage may vary.
3. If your target platform is Spring Boot or Java EE (or something else that we support), you might be interested in our commercial code scanner VUSC which parses all the configuration files, dynamic endpoint registrations in code, etc. to create a precise dummy main method. We have an academic program for non-commercial academic by eligible universities, and we have commercial licenses for the industry. VUSC uses FlowDroid, but with tons of code for platform modeling on top.

If you want more details on how dummy main methods work, have a look at my PhD thesis: https://tuprints.ulb.tu-darmstadt.de/5937/

**Comment by jimmy66688** [comment]
> Your problem is similar to Android apps, which are essentially plugins into the operating system. This design principle also applies to, e.g., Spring Boot or Java Enterprise applications. FlowDroid uses dummy main methods to simulate these interactions between platform and application, i.e., it generates a fake `main()` method, which calls the actual entry points.
> 
> You have multiple options:
> 
> 1. You implement an instance of `IEntryPointCreator` from your platform (inherit from `BaseEntryPointCreator` to make your life easier). While this approach requires some work, you can be as precise as you want in your model, also with regard to data flows between reequest processing methods.
> 2. Over-approximate using the `DefaultEntryPointCreator`, which takes a set of methods, and calls all of them in a sequence, with some heuristics on when to share objects between calls. This is a very simple solution, your mileage may vary.
> 3. If your target platform is Spring Boot or Java EE (or something else that we support), you might be interested in our commercial code scanner VUSC which parses all the configuration files, dynamic endpoint registrations in code, etc. to create a precise dummy main method. We have an academic program for non-commercial academic by eligible universities, and we have commercial licenses for the industry. VUSC uses FlowDroid, but with tons of code for platform modeling on top.
> 
> If you want more details on how dummy main methods work, have a look at my PhD thesis: https://tuprints.ulb.tu-darmstadt.de/5937/

Thank you Steven.

I've been reading around about how the `dummy main method` works, but I haven't seen a complete example. 

I know that calling a static or instance method in `dummy main method` requires complete creation of each parameter, which can be either primitive or object, how to create these parameters?

Is there an example in FlowDroid source code for this? Especially for objects, I only know in your PhD thesis that they need to be created recursively, but I need best practices.

**Comment by DeepakUniAdel** [comment]
@jimmy66688 Sorry I was trying to reach you.. Its not about the question asked here, It would be greatly appreciated if you could explain how you instrumented the Java code for sensing the "if" conditions using sink() method where can we do the instrumentation and which functions can be used for the same?

**Comment by jimmy66688** [comment]
> 

The code instrumentation is based on Soot and not FlowDroid. You can refer to Prof. Dr. Eric Bodden's blog https://www.bodden.de/2013/01/08/soot-android-instrumentation/

**Comment by DeepakUniAdel** [comment]
> > @jimmy66688 Sorry I was trying to reach you.. Its not about the question asked here, It would be greatly appreciated if you could explain how you instrumented the Java code for sensing the "if" conditions using sink() method where can we do the instrumentation and which functions can be used for the same? my email id is [ani4malabar@gmail.com](mailto:ani4malabar@gmail.com)
> 
> The code instrumentation is based on Soot and not FlowDroid. You can refer to Prof. Dr. Eric Bodden's blog https://www.bodden.de/2013/01/08/soot-android-instrumentation/

Yeah I have gone through it using the Soot active body... But my doubt is if I want to add the instrumentation to Soot output in Simple, where it needs to be done if I have to analyse the instrumented code using FlowDroid.. Can you please send me an email so that I can get your email id and can talk to you further about the issue I am facing... I don't want to deviate the discussion happening here... please

**Comment by StevenArzt** [comment]
Please try and stick to a single topic per issue. If you want to discuss a second topic, please open another issue. Otherwise, it's really hard to keep track of what is still open and what has been resolved.

**Comment by jimmy66688** [comment]
> Your problem is similar to Android apps, which are essentially plugins into the operating system. This design principle also applies to, e.g., Spring Boot or Java Enterprise applications. FlowDroid uses dummy main methods to simulate these interactions between platform and application, i.e., it generates a fake `main()` method, which calls the actual entry points.
> 
> You have multiple options:
> 
> 1. You implement an instance of `IEntryPointCreator` from your platform (inherit from `BaseEntryPointCreator` to make your life easier). While this approach requires some work, you can be as precise as you want in your model, also with regard to data flows between reequest processing methods.
> 2. Over-approximate using the `DefaultEntryPointCreator`, which takes a set of methods, and calls all of them in a sequence, with some heuristics on when to share objects between calls. This is a very simple solution, your mileage may vary.
> 3. If your target platform is Spring Boot or Java EE (or something else that we support), you might be interested in our commercial code scanner VUSC which parses all the configuration files, dynamic endpoint registrations in code, etc. to create a precise dummy main method. We have an academic program for non-commercial academic by eligible universities, and we have commercial licenses for the industry. VUSC uses FlowDroid, but with tons of code for platform modeling on top.
> 
> If you want more details on how dummy main methods work, have a look at my PhD thesis: https://tuprints.ulb.tu-darmstadt.de/5937/

I have had the pleasure of reading your PhD thesis and all the classes in the FlowDroid source code that implement the `IEntryPointCreator` interface.

I see that when creating the `dummy main method`, I just need to specify the method signature and then all the class instances, method parameters are created automatically.

What kind of precision do you mean by `as precise as you want in your model` in your reply? Does it require that I manually create each parameter in the model?

For example, Cassandra contains CRUD operations, if I need to analyze the information flow of four operations, do I need to manually create method calls for each operation corresponding to the parameters?

There is only one request processing entry point on the server side of Cassandra, and it dispatches different processing logic based on the contexts carried in the request. Do I need to prepare contexts for each of the CRUD operations? Or is the context automatically created by FlowDroid `soundness` enough? Can FlowDroid create callgraphs that cover all four curd operations? I know that the context mainly affects the point-to-set in the `SPARK` callgraphalgorithm.

Thank you Steven.

**Comment by StevenArzt** [comment]
If there is only one entry point that dispatches incoming requests based on fields inside that request, e.g., to distinguish between POST and DELETE operations, you don't need to handle that explicitly. Since the request is external data, FlowDroid assumes that it can contain arbitrary data. If there are conditionals inside the Cassandra dispatcher, FlowDroid will propagate taints into all possible targets (all then/else cases). You just need to make sure that the dummy main method contains a call to the Cassandra entry point.

My comment on precision was more about, e.g., taking the configuration of your application into account as well.
