### ISSUE TITLE
Unsoundness in flow sensitive aliasing when handling cycles in ICFG

### ISSUE THREAD

**Issue by amordahl** [secure-software-engineering/FlowDroid#501]
## Issue

There is some unsoundness in the flow sensitive alias strategy (default configuration of FlowDroid) causing unsoundness in certain situations where there are cycles in the ICFG.

## Test Case

Callbacks/Button5.apk in Droidbench 3.0.

## Expected Output

```
[main] INFO soot.jimple.infoflow.android.SetupApplication$InPlaceInfoflow - The sink staticinvoke <android.util.Log: int i(java.lang.String,java.lang.String)>("DroidBench", $r4) in method <edu.mit.button_object_allocation.Button1: void sendMessage(android.view.View)> was called with values from the following sources:
[main] INFO soot.jimple.infoflow.android.SetupApplication$InPlaceInfoflow - - $r4 = virtualinvoke r3.<android.telephony.TelephonyManager: java.lang.String getDeviceId()>() in method <edu.mit.button_object_allocation.Button1: void onCreate(android.os.Bundle)>
[main] INFO soot.jimple.infoflow.android.SetupApplication$InPlaceInfoflow - Data flow solver took 0 seconds. Maximum memory consumption: 139 MB
[main] INFO soot.jimple.infoflow.android.SetupApplication - Found 1 leaks
```

## Actual Output

FlowDroid reports no flows.

## Observations

I'm not 100% sure about this, but here's my best shot:

Here's the code for Button5.apk:

```
public class Button1 extends Activity {
	private static String imei = null;
	
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_button1);
        
        TelephonyManager telephonyManager = (TelephonyManager) getSystemService(Context.TELEPHONY_SERVICE);
	imei = telephonyManager.getDeviceId(); //source
    }

    public void sendMessage(View view){
	Log.i("DroidBench", ((Button)view).getHint().toString());  //sink on second call to sendMessage(), second click of button
	((Button)view).setHint(imei);  
    }
}
```

The source and sink are both in the sendMessage method, and will only occur if the button is clicked twice.

The relevant code I've identified is in [FlowSensitiveAliasStrategy.java](https://github.com/secure-software-engineering/FlowDroid/blob/develop/soot-infoflow/src/soot/jimple/infoflow/aliasing/FlowSensitiveAliasStrategy.java). Specifically, it is this:

```
	@Override
	public void computeAliasTaints(final Abstraction d1, final Stmt src, final Value targetValue,
			Set<Abstraction> taintSet, SootMethod method, Abstraction newAbs) {
		// Start the backwards solver
		Abstraction bwAbs = newAbs.deriveInactiveAbstraction(src);
		for (Unit predUnit : manager.getICFG().getPredsOf(src))
			bSolver.processEdge(new PathEdge<Unit, Abstraction>(d1, predUnit, bwAbs));
	}
```

Before spawning the backwards solver, the taint is derived as inactive, so when the backwards solver analyzes the sink, it will not find a flow. This is usually sound for flow sensitive analyses but will fail in test cases like Button5. I'm not sure if the problem is here or if there is another place where this should be handled.

**Comment by StevenArzt** [comment]
The actual output and expected output that you provide are identical. Can you please double-check?

This test case is indeed tricky. Deactivating the taint is correct to preserve flow-sensitivity. If this were straight-line code, there would be no leak. We only expect a leak, because the method can be executed twice by pressing the button twice. That should be handled by the dummy main method, which should call such callbacks inside a loop to model that they can be called an arbitrary number of times. Consequently, there should be a control flow that leaves ``sendMessage``, iterates the loop, and enters ``sendMessage`` again. This control flow should hit the sink with an active taint abstraction on the second loop iteration. Since an inactive abstraction is not equal to an active one, we should see both edges being propagated.

It would be great if you could have a deeper look at the issue. I suspect that there is no incoming taint for ``view.hint`` in ``sendMessage``.

Just to make sure: You are using StubDroid, i.e., the ``SummaryTaintWrapper``, right? Otherwise, you are missing the models for ``getHint`` and ``setHint`` and your taint will obviously be lost.

**Comment by amordahl** [comment]
Ah, sorry about the mixup with expected results. Just to clarify, the output I'm putting in "Expected Output" is what FlowDroid gives me if I set `dataflowsolver` to `flowinsensitive`. The actual result under the default configuration is flowdroid finds no flows (I fixed in the issue text).

The `SummaryTaintWrapper` is used by default, right? I am not setting `taintwrapper` at all.

**Comment by StevenArzt** [comment]
If you run the command-line application, the ``SummaryTaintWrapper`` is used by default. If you use FlowDroid as an API using the ``SetupApplication`` class, you need to register the taint wrapper on your own: ``SetupApplication.setTaintWrapper()``.

**Comment by amordahl** [comment]
I am using it via the command line.
