### ISSUE TITLE
Repository for Soot and Eclipse are down in Development branch

### ISSUE THREAD

**Issue by Jclavo** [secure-software-engineering/FlowDroid#548]
Hi @StevenArzt, I tried to build FlowDoid but after run `mvn install`  I got 

![image](https://user-images.githubusercontent.com/15223749/202034115-8d867c4b-bebf-4cdc-9a05-2e41dee5e2c1.png)

and I realized that the url from repositories (Soot and Eclipse) are down. Are they on maintenance? 

Below I attach some useful information

* Soot-Snapshots (app/flowdroid/soot-infoflow/pom.xml)

```
<repositories>
      <repository>
          <id>Soot-Snapshots</id>
          <url>https://ssebuild.sit.fraunhofer.de/nexus/repository/Soot/</url>
          <snapshots>
              <enabled>true</enabled>
          </snapshots>
      </repository>
</repositories>
```

![image](https://user-images.githubusercontent.com/15223749/202034860-2c5b4bde-4173-43e3-8e60-4fcfee8346ba.png)

* Eclipse (app/flowdroid/soot-infoflow-android/pom.xml)

```
       <repositories>
		<repository>
			<id>Eclipse</id>
			<url>https://ssebuild.sit.fraunhofer.de/nexus/repository/maven-mixed/</url>
		</repository>
	</repositories>
```

![image](https://user-images.githubusercontent.com/15223749/202035013-975401d0-d6bc-4adc-b52c-9d9df8e92f0f.png)

**Comment by StevenArzt** [comment]
This repository isn't supposed to work outside of the Fraunhofer SIT network. Unfortunately, we have to rely on the Soot snapshot version, because we need some of the more recent changes in Soot. The easiest way to compile FlowDroid at the moment is to clone the [Soot repository](https://github.com/soot-oss/soot), run ``mvn install`` on it, and then re-run the FlowDroid build. That way, the Soot snapshot is in your local Maven cache and the build works.

By the way, you might also want to disable tests when building FlowDroid, unless you have a proper setup of the Android SDK and the correct environment variables in place.

**Comment by Jclavo** [comment]
Thanks for the quick answer @StevenArzt , I will try your suggestion. Also, I will try the first time to run without tests and after that I do including the test suite.
And just a curiosity, Fraunhofer SIT has an open VPN by any chance?

**Comment by StevenArzt** [comment]
That's our internal VPN, so it's not open. We actually put this URL into the ``pom.xml`` to make our internal build work, it's kind of a hack. I'm really looking forward to next proper Soot release so that we can get rid of that hack.

**Comment by Jclavo** [comment]
I got it, no problem and again thanks for the help.
