### ISSUE TITLE
[Question] How to get SCC of a CFG and how to get data flow graph for a method?

### ISSUE THREAD

**Issue by FrankieYin** [secure-software-engineering/FlowDroid#59]
Hi @StevenArzt ,

I'm wondering if there are constructs or sections of code that compute the strongly connected components of a call graph/control flow graph.

Also is it possible to get the data flow graph for a method?

Kind regards,
Zhijun

**Comment by StevenArzt** [comment]
We use IFDS to create a data flow graph over the whole interproedural control flow graph. FlowDroid does not analyze methods independently. Such an approach would need a different definition of sources, unless you need a graph of all possible data flows inside the method, regardless of whether they are triggered by a source at all. Can you be more specific on what you want to achieve?

We do not compute SCCs in FlowDroi at the moment, although Soot seems to have some implementation for it. Have a look at the SCC* classes in Soot.

**Comment by StevenArzt** [comment]
If you want to use how a specific permission is used, you first need a mapping between the API methods that access a certain data type and the permission by which they are guarded. You can then define these methods as sources and all method with which data can leave the device as sinks. Afterwards, you can run a normal data flow analysis with FlowDroid to get the source-to-sink connections.

**Comment by FrankieYin** [comment]
Hi @StevenArzt ,
I've used the permission mapping data from PScout to annotate the SCC graph nodes I produced. Right now I want to use some of the identifiers in an app as sources and sinks. Could you tell me how to define the sources and sinks? And after having defined them, is it possible to know which identifiers is flowing into another identifier? Do I simply use the `runInfoflow` method of the `SetupApplication` class?
Thanks for your help!

Kind, Zhijun

**Comment by StevenArzt** [comment]
You can define sources and sinks through an implementation of the ISourceSinkManager interface. The default implementation for Android reads the SourcesAndSinks.txt file to obtain the signatures of all methods that are sources or sinks, If you want to have methods a sources or sinks, you can just use this file. Otherwise, you would need to create your own ISourceSinkManager.

For running the data flow analysis, you can call runInfoflow(), that's right.

**Comment by FrankieYin** [comment]
Hi @StevenArzt ,
I've reading FlowDroid's source code. My goal is to find name flows between identifiers in assignments and actual to formal parameter bindings, so ideally I want to be able to reuse your code, in which case I would have to create my own `ISourceSinkManager`. My question is, how do you implement an `ISourceSinkManager` given what I want to do? I've only seen the `AccessPathBasedSourceSinkManager` being used in `runInfoflow` once, so is there a way to link the `runInfoflow` with my implementation of the `ISourceSinkManager`?

Zhijun

**Comment by StevenArzt** [comment]
You can derive a class from SetupApplication and override the createSourceSinkManager() method to inject your own implementation of a source/sink manager.

**Comment by FrankieYin** [comment]
Hi @StevenArzt ,

Thank you very much for you help so far.
I was trying to use the `SourcesAndSinks.txt` to see how the default source and sink manager works in order to figure out how to implement one of my own; however I'm running into problem: when I call `runInfoflow` the methods complains "No source/sink file specified for the data flow analysis".

I'm using FlowDroid as a maven library and I put the `SourcesAndSinks.txt` file at the root directory of my project. Is this how you should use it?

Also, from what I read in the code, the parser for sources/sinks looks for signatures like `<com.example.user.app.feature.MainActivity: void method1()>`, but how do I specify which methods are the sources and which are sinks?

Kind regards,
Zhijun

**Comment by FrankieYin** [comment]
Hi,
I saw the `SourcesAndSinks.txt` in the library. I'll use that first!

**Comment by StevenArzt** [comment]
You can specify the path of the source/sink definition file using the InfoflowConfiguration object. That's also what happens in the command-line application when you specify the -s parameter. To increase usability, we provide a default file when there is no user-defined file.

Concerning the syntax of the source/sink definition: It depends on the type of input. The source/sink managers provided with FlowDroid use providers to actually read out the definition files. The easiest provider uses the syntax based on Soot method signatures that you mention. Essentially, you have

```
<com.example.user.app.feature.MainActivity: void method1()> -> _SOURCE_
```

We also have a more complex provider that parses an XML-based source/sink specification. With that specification, you can exactly pinpoint individual access paths that you want to treat as sources or sinks. For a sink method, for example, you may only want to specify one parameter as the sink, but not all of them. That only works with the XML-based format, because the simple signature-based format is not expressive enough.

**Comment by StevenArzt** [comment]
Since there has not been any further activity on this issue, I close it. In case you need more assistance, please open a new issue.
