### ISSUE TITLE
Request for merging our tool (FPC) into FlowDroid

### ISSUE THREAD

**Issue by DongjieHe** [secure-software-engineering/FlowDroid#622]
Hi FlowDroid Developers, 
Inspired by CleanDroid (https://ieeexplore.ieee.org/abstract/document/9402149), we have designed a new tool for the IFDS path edge collection. Our paper (https://dongjiehe.github.io/mypaper/ISSTA2023_FPC_Final.pdf) has been accepted by ISSTA'2023 and the tool is available at https://github.com/DongjieHe/FPC. 

We hope to contribute to Flowdroid by merging the implementation of FPC into FlowDroid. Can you tell us what to do next?

Kind regards,
Dongjie He

**Comment by StevenArzt** [comment]
Congratulations on your paper!

CleanDroid has been implemented as an alternative solver in FlowDroid to allow users to choose between the original ``FastSolver`` and CleanDroid. It would be great if you could open a merge request with your approach as another solver implementation, so that we can have all solvers in parallel. We would then run all of our unit tests on your solver, to make sure that it retains the correctness of the analyzer and that is supports all features that FlowDroid and its downstream analyses need. If everything along the entire chain works, we can think about making your solver the default, but this will likely take some time, as we need to get the feedback from all major projects that depend on FlowDroid.

**Comment by DongjieHe** [comment]
Hi Steven Arzt,
Thanks for your response.
We will first do the code review and will open a merge request in the next few days.
Kind regards,
Dongjie
