### ISSUE TITLE
(Question) Doses FlowDroid support encode to binary xml??

### ISSUE THREAD

**Issue by DuyLong97** [secure-software-engineering/FlowDroid#689]
First, I want to express my heartfelt gratitude to each and every member of FlowDroid team. I have found FlowDroid project last week and it's was amazing. But still one question I want to ask @StevenArzt. Does FlowDroid project support encode to binary XML? In my case I want to encode the AndroidManifest.xml file to binary XML. Hope can receive your feedback soon. Thank you.

**Comment by StevenArzt** [comment]
Thank you for your kind words on FlowDroid.

FlowDroid uses the ``axml`` library to read binary XML files. We essentially wrap ``axml`` to give convenient access to the Android manifest and other relevant files. There is no feature to write changes back from these abstraction, because nobody needed it yet.

However, you can directly use ``axml`` to implement writing as well. There is a class ``AXmlWriter`` that you can use. If you want to add convenient support for writing back manifest changes, you can also extend our ``ProcessManifest`` class. Feel free to create a merge request.

**Comment by DuyLong97** [comment]
Thank for replying me. I have a last question "Can we write ARSCFileParser to file"?

**Comment by StevenArzt** [comment]
Unfortunately, we have no way to write out the Android resource database. The ``ARSCFileParser`` is only intended for reading. It cannot write.

**Comment by DuyLong97** [comment]
I see. Thank you @StevenArzt
