### ISSUE TITLE
Using FlowDroid programmatically with the Soot framework.

### ISSUE THREAD

**Issue by ANter-xidian** [secure-software-engineering/FlowDroid#77]
Hi, giants.

I am working on a Java project which aims to perform forward slicing technique using the Soot framework, the global picture of my project is to convert the bytecode files to Jipmle forms and then perform forward slicing technique accordingly, however, I am new to the Soot framework, so I have done some research and found that the Soot framework doesn't support any kind of slicing techniques.

I wonder if I can use FlowDroid programmatically to perform forward slicing technique in my project?

could anyone point me in the right direction to get started with this?

Thanks in advance.
ANter.

**Comment by StevenArzt** [comment]
FlowDroid is a static data flow tracker. It can give you connections between sources and sinks, for which data from the source influences values passed to the sink. You can also get the statements along this path as long as they influence the values passed to the sink.

Whether that helps for your problem or not depends on the details of your problem. FlowDroid won't put any conditions on the data flow path, because they do not influence the data flow as such (given that FlowDroid does not attempt to evaluate conditions, we do not perform any abstract interpretation or symbolic execution). Consequently, the data flow path will usually not be executable, but is sufficient to understand why data is leaked. If you need to have conditions, you need to perform your own tracking. In general, we have created a slicer for Soot as part of the Harvester project (https://www.bodden.de/pubs/ssme16harvesting.pdf), bnut unfortunately, this is not open source code.

**Comment by ANter-xidian** [comment]
well, I think I got your points.

Thank you very much for your quick reply. @StevenArzt
