### ISSUE TITLE
Is it possible get dataflow graph from Flowdroid?

### ISSUE THREAD

**Issue by ThomasGoodMan** [secure-software-engineering/FlowDroid#94]
Hi, 
It is possible extract from FlowDroid only dataflow graph instead of Source and Sink violations?
Thanks in advice.

**Comment by StevenArzt** [comment]
The main goal of FlowDroid si to find data flows between sources and sinks. We therefore try to propagate taint abstractions only where necessary and to compact the graph wherever we can. Consequently, you can't get a full data flow graph from FlowDroid, because that wouldn't scale for large apps. If you really need a propagation graph, you can take one of the following approaches:

1) Modify ```IFDSSolver.propagate()``` to record every edge it gets. This will result in a huge, but mostly complete, graph.
2) Look at the taint abstractions that arrive at sinks and follow their predecessor chain upwards. This is how our path reconstruction algorithms work.
